"""new fields in user model

Revision ID: 04231c5aeba6
Revises: 0ff78bb428ef
Create Date: 2020-07-15 00:47:07.355505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04231c5aeba6'
down_revision = '0ff78bb428ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
